-- Hissedarlar Seed Script
-- HİSSEDARLAR LİSTESİ.md dosyasından üretilmiştir
-- Önce varsayılan kasa oluşturulur, ardından tüm hissedarlar eklenir.

BEGIN;

-- Varsayılan kasa (yoksa oluştur)
INSERT INTO kasalar (ad, para_birimi, bakiye, aciklama)
SELECT 'Ana Kasa', 'TL', 0, 'Kooperatif ana kasası'
WHERE NOT EXISTS (SELECT 1 FROM kasalar WHERE ad = 'Ana Kasa');

-- Tüm INSERT'lerde Ana Kasa'yı kullan
DO $$
DECLARE
  v_kasa_id BIGINT;
BEGIN
  SELECT id INTO v_kasa_id FROM kasalar WHERE ad = 'Ana Kasa' LIMIT 1;

  INSERT INTO hissedarlar (ad, soyad, kasa_id, aile_sira_no, yakin_adi, yakinlik_derecesi) VALUES
    ('ABDULBAKİ',        'GENCER', v_kasa_id,  1, 'ABDULBAKİ',      'KENDİSİ'),
    ('FEHİM ŞİRİN',     'GENCER', v_kasa_id,  1, 'ABDUL BAKİ',      'BABA'),
    ('ABDULHAMİT',      'GENCER', v_kasa_id,  2, 'BEŞİR',           'BABA'),
    ('DİLARA',          'GENCER', v_kasa_id,  2, 'ABDULHAMİT',      'BABA'),
    ('HAMİDE',          'GENCER', v_kasa_id,  2, 'ABDULHAMİT',      'BABA'),
    ('MAŞALLAH',        'GENCER', v_kasa_id,  2, 'ABDULHAMİT',      'BABA'),
    ('ABDULLAH',        'GENCER', v_kasa_id,  3, 'CUMA',            'BABA'),
    ('GÜNAY',           'GENCER', v_kasa_id,  3, 'ABDULLAH',        'EŞ'),
    ('ABDULLAH AZAT',   'GENCER', v_kasa_id,  4, 'MELE KEREM',      'BABA'),
    ('ABİDİN',          'GENCER', v_kasa_id,  5, 'CEMİL',           'BABA'),
    ('ABDULLAH (SELAM)','GENCER', v_kasa_id,  6, 'NAİF',            'BABA'),
    ('İSLAM',           'GENCER', v_kasa_id,  6, 'ABDULLAH',        'BABA'),
    ('ADİL',            'GENCER', v_kasa_id,  7, 'KAMİL',           'BABA'),
    ('MUHAMMET',        'GENCER', v_kasa_id,  7, 'ADİL',            'BABA'),
    ('AHMET',           'GENCER', v_kasa_id,  8, 'HACI FEHİM',      'BABA'),
    ('HÜSEYİN',         'GENCER', v_kasa_id,  8, 'AHMET',           'BABA'),
    ('SİNAN',           'GENCER', v_kasa_id,  8, 'AHMET',           'BABA'),
    ('ZARA',            'GENCER', v_kasa_id,  8, 'AHMET',           'BABA'),
    ('ÇİĞDEM',          'GENCER', v_kasa_id,  8, 'AHMET',           'EŞ'),
    ('AKİF',            'GENCER', v_kasa_id,  9, 'İSMET',           'BABA'),
    ('BAHATTİN',        'GENCER', v_kasa_id, 10, 'HACI BEKİR',      'BABA'),
    ('BİLAL',           'GENCER', v_kasa_id, 10, 'BAHATTİN',        'BABA'),
    ('BAHRİ',           'GENCER', v_kasa_id, 11, 'HACI FEHİM',      'BABA'),
    ('BAYRAM',          'GENCER', v_kasa_id, 12, 'BESİM',           'BABA'),
    ('ABDULBARİ',       'GENCER', v_kasa_id, 13, 'ABDULBARİ',       'KENDİSİ'),
    ('NİSA',            'GENCER', v_kasa_id, 13, 'ABDULBARİ',       'BABA'),
    ('UMUT',            'GENCER', v_kasa_id, 13, 'ABDULBARİ',       'BABA'),
    ('BETÜL',           'GENCER', v_kasa_id, 14, 'MESUT',           'BABA'),
    ('BİLAL',           'GENCER', v_kasa_id, 15, 'YAŞAR',           'BABA'),
    ('BURHAN',          'GENCER', v_kasa_id, 16, 'SÜLEYMAN',        'BABA'),
    ('SÜLEYMAN',        'GENCER', v_kasa_id, 16, 'BURHAN',          'BABA'),
    ('RASİME',          'GENCER', v_kasa_id, 16, 'BURHAN',          'EŞ'),
    ('CEMAL',           'GENCER', v_kasa_id, 17, 'CEMİL',           'BABA'),
    ('BEDİRHAN TURAN',  'GENCER', v_kasa_id, 17, 'CEMAL',           'BABA'),
    ('MUHAMMED EFE',    'GENCER', v_kasa_id, 17, 'CEMAL',           'BABA'),
    ('CİHAN',           'GENCER', v_kasa_id, 18, 'HAMDİN',          'BABA'),
    ('CUMA',            'GENCER', v_kasa_id, 19, 'HACI FERNAN',     'BABA'),
    ('ECVET',           'GENCER', v_kasa_id, 20, 'ECVET',           'BABA'),
    ('MUSA',            'GENCER', v_kasa_id, 20, 'ECVET',           'BABA'),
    ('EDİP',            'GENCER', v_kasa_id, 21, 'BAHRİ',           'BABA'),
    ('MİRAÇ',           'GENCER', v_kasa_id, 21, 'EDİP',            'BABA'),
    ('EMİN',            'GENCER', v_kasa_id, 22, 'HACI FEHİM',      'BABA'),
    ('ADEM',            'GENCER', v_kasa_id, 22, 'EMİN',            'BABA'),
    ('FATMANUR',        'GENCER', v_kasa_id, 22, 'EMİN',            'BABA'),
    ('MUHAMMED',        'GENCER', v_kasa_id, 22, 'EMİN',            'BABA'),
    ('EMİRHAN',         'GENCER', v_kasa_id, 23, 'BEŞİR',           'BABA'),
    ('SONER',           'GENCER', v_kasa_id, 23, 'EMİRHAN',         'BABA'),
    ('ENGİN',           'GENCER', v_kasa_id, 24, 'ŞEFİK',           'BABA'),
    ('KUMSAL MİRAY',    'GENCER', v_kasa_id, 24, 'ENGİN',           'BABA'),
    ('ERHAN',           'GENCER', v_kasa_id, 25, 'ŞEFİK',           'BABA'),
    ('ERHAN',           'GENCER', v_kasa_id, 26, 'HACI SALİH',      'BABA'),
    ('ENES TALHA',      'GENCER', v_kasa_id, 26, 'ERHAN',           'BABA'),
    ('GÜLPERİ',         'GENCER', v_kasa_id, 26, 'ERHAN',           NULL),
    ('HAMZA EGE',       'GENCER', v_kasa_id, 26, 'ERHAN',           'BABA'),
    ('HACI SALİH',      'GENCER', v_kasa_id, 26, 'ERHAN',           'OĞUL'),
    ('SİNEM',           'GENCER', v_kasa_id, 26, 'ERHAN',           NULL),
    ('ERSİN',           'GENCER', v_kasa_id, 27, 'ERSİN',           'KENDİSİ'),
    ('MELEK',           'GENCER', v_kasa_id, 27, 'ERSİN',           'EŞ'),
    ('ERSİN',           'GENCER', v_kasa_id, 28, 'HAMDİN',          'BABA'),
    ('İSMAİL',          'GENCER', v_kasa_id, 28, 'ERSİN',           'BABA'),
    ('FATİH',           'GENCER', v_kasa_id, 29, 'BAHRİ',           'BABA'),
    ('BURAK',           'GENCER', v_kasa_id, 29, 'FATİH',           'BABA'),
    ('FAYHAN',          'GENCER', v_kasa_id, 30, 'FAYHAN',          'KENDİSİ'),
    ('HAVVANUR',        'GENCER', v_kasa_id, 30, 'FAYHAN',          'BABA'),
    ('RADİYE',          'GENCER', v_kasa_id, 30, 'FAYHAN',          'EŞ'),
    ('MELİK ASAF',      'GENCER', v_kasa_id, 30, 'FAYHAN',          'BABA'),
    ('MEHMET ŞEFİK',    'GENCER', v_kasa_id, 30, 'FAYHAN',          'OĞUL'),
    ('YUSUF',           'GENCER', v_kasa_id, 30, 'FAYHAN',          'BABA'),
    ('FERDİ',           'GENCER', v_kasa_id, 31, 'CEVDET',          'BABA'),
    ('AYŞE',            'GENCER', v_kasa_id, 31, 'FERDİ',           'EŞ'),
    ('FERHAT',          'GENCER', v_kasa_id, 32, 'HACI ŞEREF',      'BABA'),
    ('MAHMUT',          'GENCER', v_kasa_id, 32, 'HACI ŞEREF',      'BABA'),
    ('SERHAT',          'GENCER', v_kasa_id, 32, 'HACI ŞEREF',      'BABA'),
    ('FIRAT',           'GENCER', v_kasa_id, 33, 'ABDULHAMİT',      'BABA'),
    ('ABDULSAMET',      'GENCER', v_kasa_id, 33, 'FIRAT',           'ABİ'),
    ('EYÜP',            'GENCER', v_kasa_id, 33, 'FIRAT',           'ABİ'),
    ('GARİP',           'GENCER', v_kasa_id, 34, 'CEMİL',           'BABA'),
    ('HACI ABDULHADİ',  'GENCER', v_kasa_id, 35, 'HACI FEHİM',      'BABA'),
    ('HİKMET',          'GENCER', v_kasa_id, 36, 'HİKMET',          'KENDİSİ'),
    ('MUHAMMET',        'GENCER', v_kasa_id, 36, 'HİKMET',          'BABA'),
    ('YUSUF',           'GENCER', v_kasa_id, 36, 'HİKMET',          'BABA'),
    ('İRFAN',           'GENCER', v_kasa_id, 37, 'İRFAN',           'KENDİSİ'),
    ('ZÜBEYİR',         'GENCER', v_kasa_id, 37, 'İRFAN',           'BABA'),
    ('RÜMEYSA',         'GENCER', v_kasa_id, 37, 'İRFAN',           'BABA'),
    ('HAVVANUR',        'GENCER', v_kasa_id, 37, 'İRFAN',           'BABA'),
    ('LEZGİN',          'GENCER', v_kasa_id, 38, 'LEZGİN',          'KENDİSİ'),
    ('ADEM UZAN',       'GENCER', v_kasa_id, 38, 'LEZGİN',          'BABA'),
    ('ASİYE NUR',       'GENCER', v_kasa_id, 38, 'LEZGİN',          'BABA'),
    ('OKAN',            'GENCER', v_kasa_id, 38, 'LEZGİN',          'BABA'),
    ('YASİN',           'GENCER', v_kasa_id, 38, 'LEZGİN',          'BABA'),
    ('LOKMAN',          'GENCER', v_kasa_id, 39, 'BEŞİR',           'BABA'),
    ('MAHŞUK',          'GENCER', v_kasa_id, 40, 'MUHSİN',          'BABA'),
    ('FATMA',           'GENCER', v_kasa_id, 40, 'MAHŞUK',          'EŞ'),
    ('MAZHAR',          'GENCER', v_kasa_id, 41, 'MEHMET ALİ',      'BABA'),
    ('MEHDİ',           'GENCER', v_kasa_id, 42, 'HACI BEKİR',      'BABA'),
    ('MEHMET',          'GENCER', v_kasa_id, 43, 'İSMET',           'BABA'),
    ('MEHMET NEZİR',    'GENCER', v_kasa_id, 44, 'HACI BEKİR',      'BABA'),
    ('EDANUR',          'GENCER', v_kasa_id, 44, 'MEHMET NEZİR',    'BABA'),
    ('ENSAR',           'GENCER', v_kasa_id, 44, 'MEHMET NEZİR',    'BABA'),
    ('NİSANUR',         'GENCER', v_kasa_id, 44, 'MEHMET NEZİR',    'BABA'),
    ('SEMİHA',          'GENCER', v_kasa_id, 44, 'MEHMET NEZİR',    'BABA'),
    ('MEHMET NURİ',     'GENCER', v_kasa_id, 45, 'CEMİL',           'BABA'),
    ('ABDULKADİR',      'GENCER', v_kasa_id, 45, 'MEHMET NURİ',     'BABA'),
    ('HİRANUR',         'GENCER', v_kasa_id, 45, 'MEHMET NURİ',     'BABA'),
    ('MEHMET SANİ',     'GENCER', v_kasa_id, 46, 'MUHSİN',          'BABA'),
    ('İZZET',           'GENCER', v_kasa_id, 46, 'MEHMET SANİ',     'BABA'),
    ('RAHİME',          'GENCER', v_kasa_id, 46, 'MEHMET SANİ',     'EŞ'),
    ('HELİN',           'GENCER', v_kasa_id, 46, 'MEHMET SANİ',     'BABA'),
    ('MUHARREM',        'GENCER', v_kasa_id, 46, 'MEHMET SANİ',     'BABA'),
    ('MEHMET ŞİRİN',    'GENCER', v_kasa_id, 47, 'MEHMET ŞİRİN',    'KENDİSİ'),
    ('SAMET',           'GENCER', v_kasa_id, 47, 'MEHMET ŞİRİN',    'BABA'),
    ('ESİN',            'GENCER', v_kasa_id, 47, 'MEHMET ŞİRİN',    'BABA'),
    ('BERFİN',          'GENCER', v_kasa_id, 47, 'MEHMET ŞİRİN',    'BABA'),
    ('MEKİ',            'GENCER', v_kasa_id, 48, 'MEHMET ALİ',      'BABA'),
    ('MEHDENİ',         'GENCER', v_kasa_id, 48, 'MEKİ',            'BABA'),
    ('İSMAİL',          'GENCER', v_kasa_id, 48, 'MEKİ',            'BABA'),
    ('RESİME',          'GENCER', v_kasa_id, 48, 'MEKİ',            'EŞ'),
    ('METİN',           'GENCER', v_kasa_id, 49, 'MUHSİN',          'BABA'),
    ('MURAT',           'GENCER', v_kasa_id, 49, 'ABDULHAMİT',      'BABA'),
    ('MÜNÜR',           'GENCER', v_kasa_id, 50, 'HACI BEKİR',      'BABA'),
    ('KERİM',           'GENCER', v_kasa_id, 50, 'MÜNÜR',           'BABA'),
    ('HAMZA',           'GENCER', v_kasa_id, 50, 'MÜNÜR',           'BABA'),
    ('ESAT',            'GENCER', v_kasa_id, 50, 'MÜNÜR',           'BABA'),
    ('NAİF',            'GENCER', v_kasa_id, 51, 'ABDULLAH',        'BABA'),
    ('MAKBULE',         'GENCER', v_kasa_id, 51, 'NAİF',            'EŞ'),
    ('ROJDA',           'GENCER', v_kasa_id, 51, 'NAİF',            'BABA'),
    ('NAİM',            'GENCER', v_kasa_id, 52, 'BESİM',           'BABA'),
    ('NECMETTİN',       'GENCER', v_kasa_id, 53, 'CEMİL',           'BABA'),
    ('NİYAZİ',          'GENCER', v_kasa_id, 54, 'OSMAN',           'BABA'),
    ('ALİ OSMAN',       'GENCER', v_kasa_id, 54, 'NİYAZİ',          'BABA'),
    ('IRMAK',           'GENCER', v_kasa_id, 54, 'NİYAZİ',          'BABA'),
    ('KEREM',           'GENCER', v_kasa_id, 54, 'NİYAZİ',          'BABA'),
    ('MERTCAN',         'GENCER', v_kasa_id, 54, 'NİYAZİ',          'BABA'),
    ('NADİME',          'GENCER', v_kasa_id, 54, 'NİYAZİ',          'EŞ'),
    ('NURULLAH',        'GENCER', v_kasa_id, 55, 'CUMA',            'BABA'),
    ('NURAN',           'GENCER', v_kasa_id, 55, 'CUMA',            'EŞ'),
    ('NURULLAH ŞİRİN',  'GENCER', v_kasa_id, 56, 'NURULLAH ŞİRİN',  'KENDİSİ'),
    ('AYTEN',           'GENCER', v_kasa_id, 56, 'NURULLAH ŞİRİN',  NULL),
    ('AZRA LİNA',       'GENCER', v_kasa_id, 56, 'NURULLAH ŞİRİN',  NULL),
    ('ÖZTAÇ',           'GENCER', v_kasa_id, 57, 'ÖZTAÇ',           'KENDİSİ'),
    ('ESMANUR',         'GENCER', v_kasa_id, 57, 'ÖZTAÇ',           'BABA'),
    ('İSA',             'GENCER', v_kasa_id, 57, 'ÖZTAÇ',           'BABA'),
    ('MUHAMET YUSUF',   'GENCER', v_kasa_id, 57, 'ÖZTAÇ',           'BABA'),
    ('SANİYE',          'GENCER', v_kasa_id, 57, 'ÖZTAÇ',           'EŞ'),
    ('TAHA',            'GENCER', v_kasa_id, 57, 'ÖZTAÇ',           'BABA'),
    ('REŞİT',           'GENCER', v_kasa_id, 58, 'NAİF',            'BABA'),
    ('SİDAR',           'GENCER', v_kasa_id, 58, 'REŞİT',           'BABA'),
    ('YASİN',           'GENCER', v_kasa_id, 58, 'REŞİT',           'BABA'),
    ('SAHİL',           'GENCER', v_kasa_id, 59, 'BESİM',           'BABA'),
    ('SALİH',           'GENCER', v_kasa_id, 60, 'HACI MEHMET',     'BABA'),
    ('ŞUAYYİP',         'GENCER', v_kasa_id, 61, 'CEMİL',           'BABA'),
    ('SERHAT',          'GENCER', v_kasa_id, 61, 'ŞUAYYİP',         'BABA'),
    ('BERİVAN',         'GENCER', v_kasa_id, 61, 'ŞUAYYİP',         'BABA'),
    ('RABİA',           'GENCER', v_kasa_id, 61, 'ŞUAYYİP',         'BABA'),
    ('ABDULLAH',        'GENCER', v_kasa_id, 61, 'ŞUAYYİP',         'BABA'),
    ('VAHDETTİN',       'GENCER', v_kasa_id, 62, 'HACI BEKİR',      'BABA'),
    ('EMRAH',           'GENCER', v_kasa_id, 62, 'VAHDETTİN',       'BABA'),
    ('FATMA',           'GENCER', v_kasa_id, 62, 'VAHDETTİN',       'BABA'),
    ('ÖMER',            'GENCER', v_kasa_id, 62, 'VAHDETTİN',       'BABA'),
    ('YAKUP',           'GENCER', v_kasa_id, 63, 'CUMA',            'BABA'),
    ('YAVUZ',           'GENCER', v_kasa_id, 64, 'HACI ŞEREF',      'BABA'),
    ('FARUK',           'GENCER', v_kasa_id, 64, 'YAVUZ',           'BABA'),
    ('YUSUF',           'GENCER', v_kasa_id, 65, 'BAHRİ',           'BABA'),
    ('ZEKİ',            'GENCER', v_kasa_id, 66, 'CEMİL',           'BABA'),
    ('MAHİR',           'GENCER', v_kasa_id, 66, 'ZEKİ',            'BABA'),
    ('MUHAMET SELİM',   'GENCER', v_kasa_id, 66, 'ZEKİ',            'BABA');

END $$;

COMMIT;
